### ISSUE TITLE
How to Run localhost on port 80.?

### ISSUE THREAD

**Issue by sandippshah** [rajkumardusad/MyServer#6]
How to Run localhost on port 80.?

Starting Server ......                                     
[Sun Apr 26 18:31:32 2020] Failed to listen on localhost:80 (reason: Permission denied)

**Comment by rajkumardusad** [comment]
Hey @sandippshah you can not run localhost on port 80 because it wrog format for localhost.
us 8080 or 8000, 1234 or any port that you want..

**Comment by sandippshah** [comment]
Yup...!

But I need access my  localhost via my costom domain in ...

**Comment by rajkumardusad** [comment]
So you can use apache or nginx server.

**Comment by sandippshah** [comment]
I'm tried Apache but
problem with port 80
Apache not working on port 80..!

**Comment by rajkumardusad** [comment]
Hey @sandippshah sorry, but i think you are trying in wrong way please try to find right way..
