### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by jumaris88** [rajkumardusad/MyServer#8]
Hy I'm trying to run "access from internet" But I get a message

```
ghhhh@localhost.run: Permission denied (publickey).

 unfortunately server stopped.
```

**Comment by jumaris88** [comment]
But previously worked well

**Comment by rajkumardusad** [comment]
Hey @jumaris88 if you have root access then try with root permission like sudo or somthing else?

**Comment by jumaris88** [comment]
But previously worked well without root.

**Comment by jumaris88** [comment]
Even I execute this code directly I get the same error

ssh -R 80:localhost:8080 ssh.localhost.run

**Comment by jumaris88** [comment]
Even I execute this code directly I get the same error

ssh -R 80:localhost:8080 ssh.localhost.run

**Comment by rajkumardusad** [comment]
Hey @jumaris88 we will try to solve this issue?
We will inform you soon.

**Comment by rajkumardusad** [comment]
Hey @jumaris88 we got it, try following command to access from internet : 
`$ ssh-keygen`
and then press enter.
it will generate ssh key then you can access you localhost from internet.

**Comment by jumaris88** [comment]
Thanks it works.
